### ISSUE TITLE
Invalid partition names

### ISSUE THREAD

**Issue by sshock** [xorangekiller/gptgen#1]
Line 948 sets the gptout.name as follows:
`memset((void *)gptout.name, 0x20, 72);`

This is probably not what is wanted.  The name is in UTF-16, so this turns the name into 36 dagger (U+0x2020) characters, i.e., "††††††††††††††††††††††††††††††††††††".

This name can be seen in tools such as AccessData's FTK Imager.

Should we set it to "Basic data partition" instead?  E.g., like so:
`memset(gptout.name, 0x00, 72);`
`memcpy(gptout.name, "B\0a\0s\0i\0c\0 \0d\0a\0t\0a\0 \0p\0a\0r\0t\0i\0t\0i\0o\0n\0", 40)`

**Comment by sshock** [comment]
Thanks.

**Comment by xorangekiller** [comment]
Thank you for the opening the PR to fix this! (As you may have noticed, I am not the original author of this code. Full credit goes to @Googulator for the ingenuity. I just rescued it from Sourceforge and wrote the build scripts.) I had to look over the code several times to convince myself that this was the right fix. Not only would I probably not have noticed the problem myself, but it wasn't even immediately obvious to me that the name is UTF-16. Seriously. Thanks.

**Comment by sshock** [comment]
Hehe, yep, no problem.  It is a pretty cool little tool.  Really saved my bacon the other day. :)
