### ISSUE TITLE
MBR to GPT conversion leaves out the GPT required MSR partition

### ISSUE THREAD

**Issue by oleimann** [xorangekiller/gptgen#5]
While working with one of NetApp's customers, we found that the resulting partitioning was missing the MSR partition,
which for Windows GPT disks is required in most recent versions of Windows.

Some software (like NetApp's SnapCenter) fails to support such disks (virtual LUN files on ONTAP storage).
Also, adding the MSR partition works, but puts it at the end, disallowing resizing or even cloning the disk.

Reference for NetApp Customers:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SCW_no_longer_enumerates_a_NetApp_LUN_after_it_has_been_converted_from_MBR_to_GPT

In NetApp I can be reached by e-mail: olaf@netapp.com (Support Department)

**Comment by xorangekiller** [comment]
First off, sorry for taking so long to respond to this. I'm not sure what happened, but I didn't see the notification, or I did and forgot about it. Either way, I'm sorry. I don't know if this is still an issue for you, but I will do my best to respond.

Thank you for linking to the NetApp support article, but unfortunately I can't view it. It requires a NetApp account, which I don't have.

However, if I am understanding correctly, the problem that you are having is not really a problem with gptgen. The Microsoft Reserved Partition (MSR) is a partition "which is created to reserve a portion of disk space for possible subsequent use by a Windows operating system installed on a separate partition" [according to Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Reserved_Partition). It is *not* required to have a valid GPT partion layout. It is typically created by the Windows installer and is only required for Windows to boot from a GPT disk. Therefore gptgen is doing a valid conversion without adding this partition. Furthermore gptgen does not *ever* add or remove partitions - it only changes the partition layout from MBR to GPT leaving the existing partitions intact. Therefore I believe that this feature is completely out of scope and will be closing this issue.

If you really want to rearrange the partitions and create the MSR, maybe you could use a partition manager like [GParted](https://gparted.org/) to do that after running gptgen? This feature is more in scope for a partition manager than gptgen.
